# Week 4 Homework Question 1

1. In order to use a module, you have to first initialize the codes so they can run and process the different commands.


In [33]:
# Two Python Math Modules

# Initilizing the arrays
import numpy as np

hi = np.arange(8, dtype = np.float_).reshape(2,2,2)
hi1 = np.array([8, 16, 20, 24])
print("hi...\n", hi)
print("\nhi1...", hi1)


# adding hi and hi1 together
hi = [0, 1, 2, 3]
hi1 = [4, 5, 6, 7]
sum_list = []




hi...
 [[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]

hi1... [ 8 16 20 24]


# Week 4 Homework Questions 3 - 12

3. An errror message for when something is wrong in the code block, without this message the program will crash. 
4. Try, Except, Else, Finially
5. NumPy is simmilar to Lists. Lists store items while NumPys only store same data types.
6. Provides a multi-dimensional array.
7. dtype gives us information about the array (kind and size)
8. Sort data and supply high-level arrays
9. arthimic operations: adding(), subtracting(), multiplying() and dividing()
10. Tuple of non-negative integers that specify the dimensions, length and size of each array
11. An array with 3 dimensions
12. Lists store varius data types while arrays store only elements of the same data types
13. If you are unsure about the information that goes in an element, you can use an empty array so you can at least have placement holders.

In [116]:
# getting the current time and date
# using Date Time
import datetime as dt

# Get Current Date and Time
now = dt.datetime.now()
print("Current Date and Time ... ", now)

# extracting the full month name from now
print("Current month:", now.month)

week4 = datetime.datetime.now()

print(week4.strftime("%B"))


Current Date and Time ...  2023-02-20 16:12:12.693063
Current month: 2
February


In [113]:
# Set a default value for the day name of Sunday.
# Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.
# Invoke this function with 2 variables.
# Invoke this function with 1 variable only

import datetime as dt
# nameday("Rachael", current.strftime(%A))

def nameday(name = "Rachael", day = "Sunday"):
    print("Hi", name,"! Happy", day, "!")
nameday("Rachael", "Sunday")


Hi Rachael ! Happy Sunday !


In [115]:
# Import NumPy, use one of the NumPy methods
# create an array with a shape of ... (2, 3, 2). 
# reshape method -- .reshape()

import numpy as np

spacecar = np.arange(12).reshape((2, 3, 2))
print("The spacecar array ...\n", spacecar)

The spacecar array ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [117]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

r = np.linspace(0, 20, num=6)
print("array r ...", r)

array r ... [ 0.  4.  8. 12. 16. 20.]


In [120]:
# make a deep copy of r from above example
# using numpy, broadcast the mulitplication of the following two arrays to a 2D array using the newaxis parameter

[0.71, 0.1, 0.24, 0.3]
[0.8, 0.59, 1.0, 1.11]

import copy 

spacecar2 = copy.deepcopy(spacecar)
