In [1]:
# using Date Time
import datetime as dt

# Get Current Date and Time
a = dt.datetime.now()
print("Current Date and Time ... ", a)

Current Date and Time ...  2023-02-17 14:38:21.001986


In [2]:
# Get just the Date

b = dt.date.today()
print("Just the date ... " , a)

Just the date ...  2023-02-17 14:38:21.001986


In [4]:
# Create a date object to represent a specific date
c = dt.datetime(2020, 5, 17)

print("Presenting a specific date ...", c)

Presenting a specific date ... 2020-05-17 00:00:00


In [8]:
# find parts of the date string
from datetime import date
today = date.today()

# Print today's year, month and day
print("Current year:", today.year)
print("Current month:", today.month)
print("Current day:", today.day)

Current year: 2023
Current month: 2
Current day: 13


In [13]:
# "strftime()" EXAMPLES
import datetime
example = datetime.datetime.now()

print("Day ... ", example.strftime("%A"))
print("Month ... ", example.strftime("%b"))

Day ...  Monday
Month ...  February


In [14]:
# basic try and exception
# here is an error
# print(x)

# This will cause an error as x is not defined
try:
    print(x)
except:
    print("An exception occurred")

An exception occurred


In [23]:
def my_message(): 
        ("It rains")
        ("next month")
print("my_message")

my_message


In [24]:
# Example of a function call
def familyName(fname):
    print(fname + " Smith")

familyName("Jerry")
familyName("Amy")
familyName("Chad")

Jerry Smith
Amy Smith
Chad Smith


In [3]:
# Function definition is here
def printInfo( name, age = 35 ): 
    # "This code below prints all info passed into this function"
    print("Name: ", name)
    print("Age ", age)

# call the printInfo function with parameters in order
printInfo("Johnny", 12)

# When using Keyword Arguments - order of parameters is not important
printInfo(age=50, name="Mimi")
printInfo(name="Mike")

Name:  Johnny
Age  12
Name:  Mimi
Age  50
Name:  Mike
Age  35


In [29]:
# Function definition is here
def summing(arg1, arg2):
    # Add both the parameters and return them."
    sumTotal = arg1 + arg2
    # print("Inside the function : ", sumTotal)
    return sumTotal

# Now you can call sum function
total = summing(10, 20)
print("The Total ...", total)

The Total ... 30


In [30]:
# Function definition is here
total = summing(10, 20)
print("The Total ...", total)

The Total ... 30


In [31]:
# This is global variable.
total = 0

# Function definition is here
def summary(arg1, arg2):
    # Add both the parameters and return them."
    innerSum = arg1 + arg2; # Here total is local variable.
    print("Inside the function local sum : ", innerSum)
    print("Inside the function global total : ", total)
    return innerSum

# Now you can call sum function
total = (summary(10, 20))

print("\nOutside the function global total : ", total)
print("Print outside the function - sum : ", innerSum)

Inside the function local sum :  30
Inside the function global total :  0

Outside the function global total :  30


NameError: name 'innerSum' is not defined

In [35]:
x = lambda a : a + 10
print(x(5))

15


Redoing Week 3 Homework in the block below:

In [40]:
# creating a list of five elements

iList = ["green", "silver", 1, 2.2, [2,4,6]]
print("iList ...", inputList)



iList ... ['green', 'silver', 1, 2.2, [2, 4, 6]]


Starting at 4.2

In [3]:
#### JUST AN INTERESTING  TEST ####
# how much memory is consumed by NumPy vs Lists
import numpy as np
import time, sys

pyList = range(1000)    # allocate a list
print("Memory size of pyList ...", sys.getsizeof(pyList)*len(pyList))

pyArray = np.arange(1000)   # allocate a NumPy array
print("Memory size of NumPy Array ...", pyArray.size*pyArray.itemsize)



Memory size of pyList ... 48000
Memory size of NumPy Array ... 4000


In [6]:
#### ANOTHER INTERESTING  TEST ####
# how fast is NumPy vs Lists
import time, sys
SIZE = 1000000

# create 2 lists and 2 arrays of equal size 
L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

# time to find the sum of lists
start = time.time()
result = [(x,y) for x,y in zip(L1,L2)]
print("List time in ms ...", (time.time()-start)*1000)

# time to find the sum of numpy arrays
start = time.time()
result = A1+A2
print("NumPy time in ms ...", (time.time()-start)*1000)

List time in ms ... 615.7200336456299
NumPy time in ms ... 86.01522445678711


In [12]:
print("school.ndim(6)")


# Example of discovering the shape and size of a Numpy Array
import numpy as np

# build an array
# `arange` creates a list of elements
# reshape the list into a matrix / array
a_2d = np.arange(12).reshape((3, 4))
print("The a_2d array ...\n", a_2d)

print("\nNumber of dimension ...", a_2d.ndim)
# shape is the number of rows (1st axis), and  number of columns (2nd axis). 
print("Shape of array ...", a_2d.shape)

# get either the number of rows, or number of columns
print("\nnumber of rows ...", a_2d.shape[0])
print("number of columns ...", a_2d.shape[1])

school.ndim(6)
The a_2d array ...
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Number of dimension ... 2
Shape of array ... (3, 4)

number of rows ... 3
number of columns ... 4


In [13]:
# Another Example: - Discovering the shape and size of a 3D NumPy Array
import numpy as np

# this is a very stylized layout of an array
# note the Tuple with a list of lists, with lists
array_example = np.array(
                            [  
                                [ [0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ],
                                [ [0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ],
                                [ [0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ],
                                [ [0, 1, 2, 3, 4], [5, 6, 7, 8, 9] ],
                                [ [0 ,1 ,2, 3, 4], [5, 6, 7, 8, 9] ] 
                            ]
                        )

# 3 dimensions/axes
print("Array dimensions / axes ...", array_example.ndim)

# 50 total size/number of elements of array
print("Total number of elements ...", array_example.size)  

# shape is the number of elements in each dimension = 5, 2, 5
print("Array shape ...", array_example.shape)

# len() returns the size of the first dimension
print("array_example length ...", len(array_example))

print("\narray_example ...\n", array_example)

Array dimensions / axes ... 3
Total number of elements ... 50
Array shape ... (5, 2, 5)
array_example length ... 5

array_example ...
 [[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]


In [15]:
# Creating an array of 6 dimensions using ndim
# with a vector containing values [2,4,6,8,10]
# and verifying the shape
import numpy as np

# creating an array of 6 dimension using ndim
arrTest = np.array([2, 4, 6, 8, 10], ndmin=6)
print("Array of 6 dimensions ...", arrTest)

# verifying the shape
print('\nshape of arrTest ...\n', arrTest.shape)

# .len() returns the size of the first dimension
print("\nlength of arrTest ...", len(arrTest))


Array of 6 dimensions ... [[[[[[ 2  4  6  8 10]]]]]]

shape of arrTest ...
 (1, 1, 1, 1, 1, 5)

length of arrTest ... 1


In [36]:
# creating Numpy Arrays -- from a list with SAME DATA TYPES
import numpy as np

a1 = np.array([1, 2, 3, 4, 5, 6])
print("a1 ...\n", a1)

a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("a2 ...\n", a2)

a1 ...
 [1 2 3 4 5 6]
a2 ...
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
# creating arrays filled with ONEs or ZEROs
import numpy as np

# build an array with 4x zeros
b = np.zeros(4)
print("b ...", b)

# build an array with 3x ones
c = np.ones(3)
print("c ...", c)

b ... [0. 0. 0. 0.]
c ... [1. 1. 1.]


In [18]:
# create an empty array
import numpy as np

d = np.empty(3)
print("d ...", d)

d ... [1. 1. 1.]


In [19]:
# create an array from `a range`
import numpy as np

# create an array with `a range` of numbers from 0 upto, but not including 5
e = np.arange(5)
print("e =", e)

e = [0 1 2 3 4]


In [21]:
# Contains `a range`` of evenly spaced intervals
# between 1st num, and 2nd num, in steps of 3rd num
import numpy as np

# Create `a range` of evenly spaced intervals
# between 1st num, and 2nd num, in steps of 3rd num
f = np.arange(2, 9, 2)
print("f ...",  f)

f ... [2 4 6 8]


In [37]:
# reshaping a NumPy 
import numpy as np

aArray = np.array([[1,2,3], [4,5,6]])
bArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("newShape1 ...\n", aArray)

newShape1 = np.reshape(aArray, 6)
print("newShape1 ...", newShape1)

newShape2 = bArray.reshape(3, 2, 2)
print("\nnewShape3 ...\n", newShape2)

newShape1 ...
 [[1 2 3]
 [4 5 6]]
newShape1 ... [1 2 3 4 5 6]

newShape3 ...
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [25]:
# reshaping using an "Unknown" dimension
import numpy as np

aArray = np.array([[1,2,3,4,5,6,7,8], [11,12,23,34,45,56,67,78]])
print("newShape1 ...\n", aArray)

newShape3 = aArray.reshape(4,-1)
print("\nnewShape3 ...\n", newShape3)

newShape1 ...
 [[ 1  2  3  4  5  6  7  8]
 [11 12 23 34 45 56 67 78]]

newShape3 ...
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 23 34]
 [45 56 67 78]]


In [46]:
# reshaping using an "Unknown" dimension
import numpy as np

aArray = np.array([[1,2,3,4,5,6,7,8], [11,12,23,34,45,56,67,78]])
print("newShape1 ...\n", aArray)

newShape3 = aArray.reshape(2,2,-1)
print("\nnewShape3 ...\n", newShape3)

newShape1 ...
 [[ 1  2  3  4  5  6  7  8]
 [11 12 23 34 45 56 67 78]]

newShape3 ...
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 23 34]
  [45 56 67 78]]]


4.3 Notes below:

In [5]:
# basic array Arithmetic operations 
import numpy as np

# Initializing the arrays
arr = np.arange(12, dtype = np.float_).reshape(3, 4) 
arr1 = np.array([6, 12, 15, 18]) 
print("arr ...\n", arr)
print("\narr1 ...\n", arr1)


# Example 1: Adding the two arrays
arr2 = np.add(arr, arr1)
print("\nAddition ...\n", arr2)

# Example 2: Subtracting the two arrays
arr2 = np.subtract(arr, arr1)
print("\nSubtraction ...\n", arr2)

# Example 3: Multiplying the two arrays
arr2 = np.multiply(arr, arr1)
print("\nMultiplication ...\n", arr2)

# Example 4: Dividing the two arrays
arr2 = np.divide(arr, arr1)
print("\nDivision ...\n", arr2)

# Example 5: Use numpy.power() 
# to calculating exponents of an array of numbers
arr = np.array([5, 3, 6, 9, 2, 4]) 
arr2 = np.power(arr,3)
print("\nPower 3 ...\n", arr2)

# Example 6: Use numpy.power() with two arrays
arr = [2, 4, 6, 5, 3]
arr1 = [2, 3, 5, 4, 1]
arr2 = np.power(arr,arr1)
print("\nPower of arrays ...\n", arr2)

# Example 7: Use numpy.reciprocal() function
arr = np.array([50, 1.34, 3, 1, 25]) 
arr2 = np.reciprocal(arr)
print("\nReciprocal1 ...\n", arr2)

# Example 8: Use reciprocal function
arr = np.array([75], dtype = int) 
arr2 = np.reciprocal(arr) 
print("\nReciprocal2 ...\n", arr2)

# Example 9: Use numpy.mod() function
arr = np.array([7,16, 25]) 
arr1 = np.array([4,8,6]) 
arr2 = np.mod(arr,arr1) 
print("\nMod function ...\n", arr2)

# Example 10: Use numpy.remainder() function
arr = np.array([7,16, 25]) 
arr1 = np.array([4,8,6]) 
arr2 = np.remainder(arr,arr1) 
print("\nRemainder ...\n", arr2)


arr ...
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

arr1 ...
 [ 6 12 15 18]

Addition ...
 [[ 6. 13. 17. 21.]
 [10. 17. 21. 25.]
 [14. 21. 25. 29.]]

Subtraction ...
 [[ -6. -11. -13. -15.]
 [ -2.  -7.  -9. -11.]
 [  2.  -3.  -5.  -7.]]

Multiplication ...
 [[  0.  12.  30.  54.]
 [ 24.  60.  90. 126.]
 [ 48. 108. 150. 198.]]

Division ...
 [[0.         0.08333333 0.13333333 0.16666667]
 [0.66666667 0.41666667 0.4        0.38888889]
 [1.33333333 0.75       0.66666667 0.61111111]]

Power 3 ...
 [125  27 216 729   8  64]

Power of arrays ...
 [   4   64 7776  625    3]

Reciprocal1 ...
 [0.02       0.74626866 0.33333333 1.         0.04      ]

Reciprocal2 ...
 [0]

Mod function ...
 [3 0 1]

Remainder ...
 [3 0 1]


In [11]:
# comparison operations
import numpy as np

data2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\ndata2 original array ...", data2)
# find all elements < 5
print("data2 elements < 5 ...", data2[data2 < 5])

# find all elements >= 5
five_up = data2 >= 5
print("data2 elements >= 5 ...", data2[five_up])

# or

# find all elements >= 5
five_up = data2 >= 5
print("data2 elements >= 5 ...", data2[data2 >= 5])

# using modulo, find all elements divisible by 2
divisible_by_2 = data2[data2 % 2 == 0]
print("data2 elements divisible_by_2 ...", divisible_by_2)




data2 original array ... [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
data2 elements < 5 ... [1 2 3 4]
data2 elements >= 5 ... [ 5  6  7  8  9 10 11 12]
data2 elements >= 5 ... [ 5  6  7  8  9 10 11 12]
data2 elements divisible_by_2 ... [ 2  4  6  8 10 12]


In [12]:
# simplest broadcasting  - an array and a scalar value are combined
from numpy import array

a = array([1.0,2.0,3.0])
b = 2.0     # size of 1

print(a * b)

[2. 4. 6.]


In [13]:
# add a 1-D array broadcast to a 2-D array
from numpy import array

arr2D = array([[ 0.0,  0.0,  0.0],
            [10.0, 10.0, 10.0],
            [20.0, 20.0, 20.0],
            [30.0, 30.0, 30.0]])

arr1D = array([1.0, 2.0, 3.0])

print(arr2D + arr1D)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [14]:
# transforming arrays for Broadcasting with`newaxis`
from numpy import array, newaxis

aa = array([0.0, 10.0, 20.0, 30.0])
bb = array([1.0, 2.0, 3.0])

print("The sum of aa and bb ...\n")
print(aa[:,newaxis] + bb)

The sum of aa and bb ...

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [15]:
## another example of Broadcasting arrays
import numpy as np

# a (3, 4)-shaped array
x = np.array(
        [[-0.0, -0.1, -0.2, -0.3], 
        [-0.4, -0.5, -0.6, -0.7], 
        [-0.8, -0.9, -1.0, -1.1]]
)

# a (4,)-shaped array
y = np.array([1, 2, 3, 4])

# multiplying a shape-(4,) array --> y
# with a shape-(3, 4) array --> x
# `y` is multiplied by each row of `x`

print("arrays x * y ...\n", x * y)

arrays x * y ...
 [[-0.  -0.2 -0.6 -1.2]
 [-0.4 -1.  -1.8 -2.8]
 [-0.8 -1.8 -3.  -4.4]]


In [16]:
# Assigning variables using multi assignment
tt = ([ [ [0, 1, 2, 3], [4, 5, 6, 7] ],
        [ [10, 11, 12, 13], [14, 15, 16, 17] ],
        [[20, 21, 22, 23], [24, 25, 26, 27] ] ])

a, b, c = tt

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("The data type of c ...", type(c))

# further unpack the "a" variable
a0, a1 = a
print("\nFurther unpacking a ...")
print("a0 = ", a0)
print("a1 = ", a1)
print("The data type of a1 ...", type(a1))

a =  [[0, 1, 2, 3], [4, 5, 6, 7]]
b =  [[10, 11, 12, 13], [14, 15, 16, 17]]
c =  [[20, 21, 22, 23], [24, 25, 26, 27]]
The data type of c ... <class 'list'>

Further unpacking a ...
a0 =  [0, 1, 2, 3]
a1 =  [4, 5, 6, 7]
The data type of a1 ... <class 'list'>


In [17]:
# Unpacking a series of nested elements
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],
        [ [20, 21, 22, 23], [34, 35, 36, 37] ],
        [[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],
    [[i,j,k,l],[m,n,o,p]],
    [[q,r,s,t],[u,v,w,x]]] = example

print("1st group ...", a, b, c, d)
print("2nd group ...", m, n, o, p)
print("last bunch ...", q, r, s, t, u, v, w, x)

# else using the overflow astrix 
[[[aa,bb,cc,dd], [ee,ff,gg,hh]], *zz] = example

print("\nThe variables aa, bb, to hh ...")
print(aa,bb,cc,dd,ee,ff,gg, hh)

print("\nThe collective variable zz ...")
print(zz)

1st group ... 0 1 2 3
2nd group ... 34 35 36 37
last bunch ... 40 41 42 43 54 55 56 57

The variables aa, bb, to hh ...
0 1 2 3 14 15 16 17

The collective variable zz ...
[[[20, 21, 22, 23], [34, 35, 36, 37]], [[40, 41, 42, 43], [54, 55, 56, 57]]]


In [2]:
# NumPy concatenation
import numpy as np

arrayA= np.array([1, 2, 3, 4])
arrayB = np.array([5, 6, 7, 8])

arrCombo = np.concatenate((arrayA, arrayB))
print("Print arrCombo ...", arrCombo)


# More Concatenation
arrayX = np.array([[2, 1], [3, 4]])
arrayY = np.array([[5, 6]])
arrayZ = np.array([[8, 7], [9, 10], [12, 11]])

arrayC = np.concatenate((arrayZ, arrayX, arrayY), axis=0)
print("\nAnd arrayC ...\n", arrayC)

arrayCSsort = np.sort(arrayC)
# print ("\narrayC sorted ...\n", arrayCSsort)

newShape = arrayCSsort.reshape(2, 2, 3)
# print ("\nNew shape ...\n", newShape)

Print arrCombo ... [1 2 3 4 5 6 7 8]

And arrayC ...
 [[ 8  7]
 [ 9 10]
 [12 11]
 [ 2  1]
 [ 3  4]
 [ 5  6]]


In [25]:
# Sorting NumPy arrays ...
import numpy as np

# sorting a 1-D array
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr1sort = np.sort(arr1)
print("arr1 ...", arr1sort)

# Sorting a 2-D array:
# on a 2-D array both tuples will be sorted
arr2 = np.array([[3, 2, 4], [5, 0, 1]])
print("arr2 ...\n", np.sort(arr2))

# Sorting an array of strings alphabetically:
arr3 = np.array(['banana', 'cherry', 'apple'])
print("arr3 ...", np.sort(arr3))

# Sorting a boolean array:
arr4 = np.array([True, False, True])
print("arr4 ...", np.sort(arr4))

# sorting a 2D array
arr5 = np.array([[101, 112, 133, 224],
                [235, 76, 207, 148],
                [319, 110, 338, 174]])
print("\narr5 ...\n", np.sort(arr5, axis= 1))

# sorting a 3D array
arr6 = np.array([[[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]],
                [[12, 11, 13, 23], [23, 7, 12, 14], [31, 34, 33, 17]],
                [[10, 6, 13, 22], [34, 7, 20, 14], [31, 34, 33, 7]]])
print("\narr6 ...\n", np.sort(arr6, axis= 2))


arr1 ... [1 2 3 4 5 6 7 8]
arr2 ...
 [[2 3 4]
 [0 1 5]]
arr3 ... ['apple' 'banana' 'cherry']
arr4 ... [False  True  True]

arr5 ...
 [[101 112 133 224]
 [ 76 148 207 235]
 [110 174 319 338]]

arr6 ...
 [[[10 11 13 22]
  [ 7 14 20 23]
  [11 17 31 33]]

 [[11 12 13 23]
  [ 7 12 14 23]
  [17 31 33 34]]

 [[ 6 10 13 22]
  [ 7 14 20 34]
  [ 7 31 33 34]]]


In [ ]:
# Sorting NumPy arrays ...
import numpy as np

# sorting a 1-D array
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr1sort = np.sort(arr1)
print("arr1 ...", arr1sort)

# Sorting a 2-D array:
# on a 2-D array both tuples will be sorted
arr2 = np.array([[3, 2, 4], [5, 0, 1]])
print("arr2 ...\n", np.sort(arr2))

# Sorting an array of strings alphabetically:
arr3 = np.array(['banana', 'cherry', 'apple'])
print("arr3 ...", np.sort(arr3))

# Sorting a boolean array:
arr4 = np.array([True, False, True])
print("arr4 ...", np.sort(arr4))

# sorting a 2D array
arr5 = np.array([[101, 112, 133, 224],
                [235, 76, 207, 148],
                [319, 110, 338, 174]])
print("\narr5 ...\n", np.sort(arr5, axis= 1))

# sorting a 3D array
arr6 = np.array([[[10, 11, 13, 22], [23, 7, 20, 14], [31, 11, 33, 17]],
                [[12, 11, 13, 23], [23, 7, 12, 14], [31, 34, 33, 17]],
                [[10, 6, 13, 22], [34, 7, 20, 14], [31, 34, 33, 7]]])
print("\narr6 ...\n", np.sort(arr6, axis= 2))


In [26]:
# `argsort` returns the Index Numbers of elements in order
import numpy as np

xx = np.array([2, 1, 4, 3, 5])
xx1sorted = np.argsort(xx)
print(xx1sorted)

[1 0 3 2 4]


In [27]:
# Unpacking a series of nested elements
example = ([ [ [0, 1, 2, 3], [14, 15, 16, 17] ],
        [ [20, 21, 22, 23], [34, 35, 36, 37] ],
        [[40 ,41 ,42, 43], [54, 55, 56, 57] ] ])

[[[a,b,c,d], [e,f,g,h]],
    [[i,j,k,l],[m,n,o,p]],
    [[q,r,s,t],[u,v,w,x]]] = example

print("1st group ...", a, b, c, d)
print("2nd group ...", m, n, o, p)
print("last bunch ...", q, r, s, t, u, v, w, x)

# else using the overflow astrix 
[[[aa,bb,cc,dd], [ee,ff,gg,hh]], *zz] = example

print("\nThe variables aa, bb, to hh ...")
print(aa,bb,cc,dd,ee,ff,gg, hh)

print("\nThe collective variable zz ...")
print(zz)


# When you get to the 26th alphabet on converting elements, how do you keep counting so you don't have an overflow? 

1st group ... 0 1 2 3
2nd group ... 34 35 36 37
last bunch ... 40 41 42 43 54 55 56 57

The variables aa, bb, to hh ...
0 1 2 3 14 15 16 17

The collective variable zz ...
[[[20, 21, 22, 23], [34, 35, 36, 37]], [[40, 41, 42, 43], [54, 55, 56, 57]]]
